name: Dump event payload

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  Comment:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Step 1 - Dumping Github Event Payload"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
