# This is a basic workflow to help you get started with Actions

name: Hello World Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Hello:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Step 1 - Say a simple message
        run: echo "Hello World"
        shell: bash
      - name: Step 2 - Using prewritten Checkout actions to load repo
        uses: actions/checkout@v2
      - name: Step 3 - Using prewritten Checkout actions to print repo name
        run: echo "The {{ github.repository }} has been added to the runner"
        shell: bash
       
  Bye:
    runs-on: ubuntu-latest
    steps:
      - name: Final Step - Time to Say Bye
        run: echo "Bye Bye!!!"
        shell: bash
