name: Testing Trigger Words

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump Github Event Payload"
        shell: bash
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: "Check github.ref"
        shell: bash
        run: echo '${{ toJSON(github.ref) }}' | jq
      - name: "Check trigger word present or not"
        if: contains(github.event.comment.body, '/my-trigger-word')
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks **@${{ github.event.issue.user.login }}** for commenting on this issue. We have detected your trigger word.
          reactions: '+1'
  ChatOps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Get the latest SHA for the PR that was commented on"
        id: chatops
        if: contains(github.event.comment.body, '/get-runs')
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/get-runs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Print info"
        run: echo '${{ toJSON(steps.chatops) }}'
      - name: "Get Runs Using SHA"
        id: wandb
        uses: machine-learning-apps/wandb-action@master
        with:
          PROJECT_NAME: "vsher/huggingface"
          RUN_ID: ${{ steps.chatops.outputs.TRAILING_TOKEN }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          DEBUG: 'true'
      - name: "Check to see wandb output..."
        run: echo '${{ toJSON(steps.wandb) }}'
        shell: bash
      - name: "Run pwd and ls"
        run: |
          pwd
          ls ${{ github.workspace }}
      - name: "Testing artifact upload"
        run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt
      - name: "Upload dummy artifact"
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
          
      - name: Upload csv
        if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: wandb_report
          path: wandb_report.csv
          
#       - name: "Download csv artifact"
#         uses: actions/download-artifact@master
#         with:
#           name: my-artifact
#           path: path/to/artifact/world.txt
      - name: "print in terminal already created artifact"
        run: cat path/to/artifact/world.txt
        
      - name: "Print csv data"
        if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt-get install python3-setuptools
          pip3 install wheel 
          pip3 install pandas==0.25.1 tabulate==0.8.5 requests==2.22.0
          python3 action_files/wandb_results.py
        env:
          PR_NUM: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



        


