name: Testing Trigger Words

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump Github Event Payload"
        shell: bash
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: "Check github.ref"
        shell: bash
        run: echo '${{ toJSON(github.ref) }}' | jq
      - name: "Check trigger word present or not"
        if: contains(github.event.comment.body, '/my-trigger-word')
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks **@${{ github.event.issue.user.login }}** for commenting on this issue. We have detected your trigger word.
          reactions: '+1'
  ChatOps:
    runs-on: ubuntu-latest
    steps:
      - name: "Get the latest SHA for the PR that was commented on"
        id: chatops
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/get-runs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Print info"
        run: echo '${{ toJSON(steps.chatops) }}'
      - name: "Get Runs Using SHA"
        id: wandb
        uses: machine-learning-apps/wandb-action@master
        with:
          PROJECT_NAME: "vsher/huggingface"
          RUN_ID: ${{ steps.chatops.outputs.TRAILING_TOKEN }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          DEBUG: 'true'
      - name: "Check to see wandb output..."
        run: echo '${{ toJSON(steps.wandb) }}'
        shell: bash
        
      - name: Copy Repository Contents
        uses: actions/checkout@master

      - name: create deployment
        if: steps.wandb.outputs.BOOL_SINGLE_RUN
        run: |
          pip3 install requests
          python3 action_files/create_deployment.py
          # curl -d "{\"ref\": \"$BRANCH_NAME\", \"payload\": {\"wandb_run_id\": \"$RUN_ID\"}}" -H "Authorization: token $TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/deployments
        env:
          RUN_ID: ${{ steps.chatops.outputs.TRAILING_TOKEN }}
          BRANCH_NAME: ${{ steps.chatops.outputs.BRANCH_NAME }}
          TOKEN: ${{ steps.chatops.outputs.APP_INSTALLATION_TOKEN }}
        
#   WandB: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Get Runs Using SHA"
#         uses: machine-learning-apps/wandb-action@master
#         with:
#           PROJECT_NAME: ${{ format('{0}/{1}', secrets.WANDB_ENTITY, secrets.WANDB_PROJECT) }}
#           FILTER_GITHUB_SHA: ${{ steps.chatops.outputs.SHA }}
#           BASELINE_TAGS: "['baseline', 'reference']"
#           DISPLAY_METRICS: "['accuracy', 'loss', 'best_val_acc', 'best_val_loss', '_runtime']"
#           WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
#           DEBUG: 'true'

