name: Testing Trigger Words

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump Github Event Payload"
        shell: bash
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: "Check github.ref"
        shell: bash
        run: echo '${{ toJSON(github.ref) }}' | jq
      - name: "Check trigger word present or not"
        if: contains(github.event.comment.body, '/my-trigger-word')
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks **@${{ github.event.issue.user.login }}** for commenting on this issue. We have detected your trigger word.
          reactions: '+1'
  WandB:
    runs-on: ubuntu-latest
    steps:
      - name: "Get the latest SHA for the PR that was commented on"
        id: chatops
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/get-runs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Print info"
        run: echo '${{ toJSON(steps.chatops) }}'

