name: Printing WandB Runs in PR Comments 

on:
  workflow_dispatch:
  issue_comment:
    types: [created]
    
jobs:
  WandB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Get the latest SHA for the PR that was commented on"
        id: chatops
        if: contains(github.event.comment.body, '/get-runs')
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/get-runs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "Print info"
        run: echo '${{ toJSON(steps.chatops) }}'
        
      - name: "Get Runs Using SHA"
        id: wandb
        uses: machine-learning-apps/wandb-action@master
        with:
          PROJECT_NAME: "vsher/huggingface"
          RUN_ID: ${{ steps.chatops.outputs.TRAILING_TOKEN }}
          BASELINE_TAGS: "['baseline', 'reference']"
          DISPLAY_METRICS: "['eval/accuracy', 'eval/loss']"
          DISPLAY_CONFIG_VARS: "['num_train_epochs', 'num_hidden_layers']"
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          DEBUG: 'true'
          
      - name: "Check to see wandb output..."
        run: echo '${{ toJSON(steps.wandb) }}'
        shell: bash
          
      - name: Upload csv
        if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: wandb_report
          path: wandb_report.csv
        
      - name: "Print csv data"
        if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install wheel 
          pip install pandas tabulate requests
          python action_files/wandb_results.py
        env:
          PR_NUM: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



     
